processes:
  - apache: "Apache Services"
listening:
  tcp:
    - 2222: "Test SSH"
    - 32400-32401: "Test Services"
  udp:
    - 53: "Test DNS"
files:
  - "/etc/apache2.conf": [0,100000]
  - "~/test": [1,-1]
services:
  - apache
